# database/python/repositories.py

"""
Database repositories for the Gmail AI Agent.

This module provides helper functions to interact with Postgres via SQLAlchemy:

- create_workflow_run(...)
- update_workflow_status(...)
- log_email_action(...)
- save_daily_summary(...)

All low-level DB access should go through these functions so the rest of
the app does not need to know about ORM details.
"""

from __future__ import annotations

from datetime import datetime, date
from typing import Optional, Dict, Any

from sqlalchemy.orm import Session

from .base import SessionLocal
from .models import WorkflowRun, EmailLog, DailySummary


# --------------------------------------------------------------------
# Session helper
# --------------------------------------------------------------------
def get_db() -> Session:
    """
    Create and return a new database session.

    The caller is responsible for closing it (or use try/finally).
    """
    return SessionLocal()


# --------------------------------------------------------------------
# workflow_runs helpers
# --------------------------------------------------------------------
def create_workflow_run(
    thread_id: Optional[str],
    task: Optional[str],
) -> str:
    """
    Create a new workflow run record.

    Args:
        thread_id: An optional thread identifier (user/session/thread).
        task: The initial task name, e.g. "process_inbox" or "daily_summary".
              Can be "unknown" at creation time.

    Returns:
        The run_id (string) of the created WorkflowRun.
    """
    db = get_db()
    try:
        run = WorkflowRun(
            thread_id=thread_id,
            task=task or "unknown",
            status="running",
            started_at=datetime.utcnow(),
        )
        db.add(run)
        db.commit()
        db.refresh(run)
        return str(run.run_id)
    finally:
        db.close()


def update_workflow_status(
    run_id: str,
    status: str,
    result: Optional[Dict[str, Any]] = None,
) -> None:
    """
    Update the status (and optionally result) of an existing workflow run.

    Args:
        run_id: ID of the workflow run.
        status: New status, e.g. "completed", "failed".
        result: Optional dictionary with final result/summary.
    """
    db = get_db()
    try:
        run: Optional[WorkflowRun] = (
            db.query(WorkflowRun)
            .filter(WorkflowRun.run_id == run_id)
            .first()
        )
        if not run:
            return

        run.status = status
        run.finished_at = datetime.utcnow()
        if result is not None:
            run.result = result

        db.commit()
    finally:
        db.close()


# --------------------------------------------------------------------
# email_logs helpers
# --------------------------------------------------------------------
def log_email_action(
    message_id: Optional[str],
    thread_id: Optional[str],
    subject: Optional[str],
    sender: Optional[str],
    action: Optional[str],
    label_applied: Optional[str],
    reply_text: Optional[str],
) -> None:
    """
    Insert a log entry for an email that was processed.

    Args:
        message_id: Gmail message ID.
        thread_id: Gmail thread ID.
        subject: Email subject line.
        sender: Sender email address.
        action: What the agent did (e.g. "reply", "label", "spam", "ignore").
        label_applied: Applied label name, if any.
        reply_text: Reply body sent, if any.
    """
    db = get_db()
    try:
        entry = EmailLog(
            message_id=message_id,
            thread_id=thread_id,
            subject=subject,
            sender=sender,
            action=action,
            label_applied=label_applied,
            reply_text=reply_text,
            processed_at=datetime.utcnow(),
        )
        db.add(entry)
        db.commit()
    finally:
        db.close()


# --------------------------------------------------------------------
# daily_summaries helpers
# --------------------------------------------------------------------
def save_daily_summary(
    summary_text: str,
    for_date: Optional[date] = None,
) -> None:
    """
    Store a daily summary in the database.

    Args:
        summary_text: The summary generated by the agent.
        for_date: The date this summary belongs to (defaults to today).
    """
    db = get_db()
    try:
        summary = DailySummary(
            summary_date=for_date or date.today(),
            summary_text=summary_text,
            created_at=datetime.utcnow(),
        )
        db.add(summary)
        db.commit()
    finally:
        db.close()
